export const registry = {
  "accordion": { "fileName": "Accordion.svelte" },
  "alert": { "fileName": "Alert.svelte" },
  "avatar": { "fileName": "Avatar.svelte" },
  "badge": { "fileName": "Badge.svelte" },
  "breadcrumb": { "fileName": "Breadcrumb.svelte" },
  "button": { "fileName": "Button.svelte" },
  "button-group": { "fileName": "ButtonGroup.svelte" },
  "card": { "fileName": "Card.svelte" },
  "carousel": { "fileName": "Carousel.svelte" },
  "checkbox": { "fileName": "Checkbox.svelte" },
  "command": { "fileName": "Command.svelte" },
  "datepicker": { 
    "fileName": "DatePicker.svelte",
    "deps": ["flatpickr"],
    "styles": ["flatpickr/dist/flatpickr.css"]
  },
  "dialog": { "fileName": "Dialog.svelte" },
  "dropdown-menu": { "fileName": "DropdownMenu.svelte" },
  "empty": { "fileName": "Empty.svelte" },
  "field": { "fileName": "Field.svelte" },
  "input": { "fileName": "Input.svelte" },
  "input-otp": { "fileName": "InputOTP.svelte" },
  "item": { "fileName": "Item.svelte" },
  "kbd": { "fileName": "Kbd.svelte" },
  "label": { "fileName": "Label.svelte" },
  "pagination": { "fileName": "Pagination.svelte" },
  "popover": { "fileName": "Popover.svelte" },
  "progress": { "fileName": "Progress.svelte" },
  "radio": { "fileName": "Radio.svelte" },
  "resizable": { 
    "fileName": "Resizable.svelte",
    "deps": ["split.js"] 
  },
  "select": { "fileName": "Select.svelte" },
  "sheet": { "fileName": "Sheet.svelte" },
  "sidebar": { "fileName": "Sidebar.svelte" },
  "skeleton": { "fileName": "Skeleton.svelte" },
  "slider": { "fileName": "Slider.svelte" },
  "spinner": { "fileName": "Spinner.svelte" },
  "switch": { "fileName": "Switch.svelte" },
  "table": { "fileName": "Table.svelte" },
  "tabs": { "fileName": "Tabs.svelte" },
  "textarea": { "fileName": "Textarea.svelte" },
  "toast": { "fileName": "Toaster.svelte" },
  "tooltip": { "fileName": "Tooltip.svelte" }
};